-- Oracle Partitioning & Full Schema
-- 1. todos: List Partitioning (Active vs Done)
-- 2. activity_logs: Interval Range Partitioning (Automatic monthly partitions)

SET SQLBLANKLINES ON;

-- Cleanup (Reverse dependency order)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE activity_logs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE todo_categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE todo_collaborators CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE related_todos CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE comments CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE todos CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ==========================================
-- 1. USERS & CATEGORIES
-- ==========================================
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    full_name VARCHAR2(100),
    avatar_url VARCHAR2(255),
    bio CLOB,
    is_active NUMBER(1) DEFAULT 1,
    email_verified NUMBER(1) DEFAULT 0,
    phone VARCHAR2(20),
    date_of_birth DATE,
    preferences CLOB, -- JSON
    metadata CLOB, -- JSON
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add JSON constraints for JSON columns (Oracle 12c+)
ALTER TABLE users ADD CONSTRAINT ensure_users_pref_json CHECK (preferences IS JSON);
ALTER TABLE users ADD CONSTRAINT ensure_users_meta_json CHECK (metadata IS JSON);

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(50) NOT NULL,
    color VARCHAR2(7),
    icon VARCHAR2(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cat_user_name UNIQUE (name, user_id),
    CONSTRAINT fk_cat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ==========================================
-- 2. TODOS TABLE (Partitioned)
-- ==========================================
CREATE TABLE todos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    uuid VARCHAR2(36) DEFAULT REGEXP_REPLACE(rawtohex(sys_guid()), '([A-F0-9]{8})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{12})', '\1-\2-\3-\4-\5') NOT NULL,
    user_id NUMBER NOT NULL, -- Logical FK
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    priority NUMBER DEFAULT 3,
    due_date TIMESTAMP WITH TIME ZONE,
    
    -- Extended fields
    due_time TIMESTAMP, -- Oracle doesn't have TIME
    due_datetime TIMESTAMP WITH TIME ZONE,
    estimated_hours NUMBER(5,2),
    actual_hours NUMBER(5,2),
    completion_percentage NUMBER(3) DEFAULT 0,
    tags CLOB, -- JSON
    attachments CLOB, -- JSON
    checklist CLOB, -- JSON
    custom_fields CLOB, -- JSON
    color_code VARCHAR2(7),
    position NUMBER,
    is_recurring NUMBER(1) DEFAULT 0,
    recurrence_pattern VARCHAR2(50),
    difficulty_level NUMBER(3),
    reward_points NUMBER,
    cost NUMBER,
    latitude NUMBER,
    longitude NUMBER,
    short_code VARCHAR2(20),
    long_description CLOB,
    notes CLOB,
    
    -- Oracle specific types
    xml_data XMLTYPE,
    interval_ds INTERVAL DAY TO SECOND,
    year_month_interval INTERVAL YEAR TO MONTH,
    raw_data RAW(2000),

    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    reminder_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Partition Key must be in PK
    CONSTRAINT pk_todos PRIMARY KEY (id, status),
    CONSTRAINT chk_todo_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled', 'archived'))
)
PARTITION BY LIST (status) (
    PARTITION p_active VALUES ('pending', 'in_progress'),
    PARTITION p_done VALUES ('completed', 'cancelled', 'archived'),
    PARTITION p_other VALUES (DEFAULT)
);

ALTER TABLE todos ADD CONSTRAINT ensure_todos_tags_json CHECK (tags IS JSON);
ALTER TABLE todos ADD CONSTRAINT ensure_todos_attach_json CHECK (attachments IS JSON);

CREATE INDEX idx_todos_user ON todos(user_id) LOCAL;
CREATE INDEX idx_todos_created ON todos(created_at) LOCAL;


-- ==========================================
-- 3. RELATED TABLES
-- ==========================================
CREATE TABLE todo_categories (
    todo_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT pk_todo_cat PRIMARY KEY (todo_id, category_id),
    CONSTRAINT fk_todo_cat_cat FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    content CLOB NOT NULL,
    is_edited NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE todo_collaborators (
    todo_id NUMBER NOT NULL,
    collaborator_id NUMBER NOT NULL,
    CONSTRAINT pk_todo_collab PRIMARY KEY (todo_id, collaborator_id)
);

CREATE TABLE related_todos (
    todo_id NUMBER NOT NULL,
    related_todo_id NUMBER NOT NULL,
    relation_type VARCHAR2(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_related_todos PRIMARY KEY (todo_id, related_todo_id)
);

-- ==========================================
-- 4. ACTIVITY LOGS TABLE (Partitioned)
-- ==========================================
CREATE TABLE activity_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    todo_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50) NOT NULL,
    details CLOB,
    ip_address VARCHAR2(45),
    user_agent CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_activity_logs PRIMARY KEY (id, created_at)
)
PARTITION BY RANGE (created_at) 
(
    PARTITION p_old     VALUES LESS THAN (TIMESTAMP '2023-01-01 00:00:00'),
    PARTITION p_2023    VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00'),
    PARTITION p_2024    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
    PARTITION p_2025    VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'),
    PARTITION p_future  VALUES LESS THAN (MAXVALUE)
);

ALTER TABLE activity_logs ADD CONSTRAINT ensure_logs_details_json CHECK (details IS JSON);

CREATE INDEX idx_logs_user ON activity_logs(user_id) LOCAL;
CREATE INDEX idx_logs_action ON activity_logs(action) LOCAL;

