-- Oracle Partitioning
-- 1. todos: List Partitioning (Active vs Done)
-- 2. activity_logs: Interval Range Partitioning (Automatic monthly partitions)

-- Cleanup
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE activity_logs CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE todos CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ==========================================
-- 1. TODOS TABLE
-- ==========================================
CREATE TABLE todos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    uuid VARCHAR2(36) DEFAULT REGEXP_REPLACE(rawtohex(sys_guid()), '([A-F0-9]{8})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{12})', '\1-\2-\3-\4-\5') NOT NULL,
    user_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    priority NUMBER DEFAULT 3,
    due_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_todos PRIMARY KEY (id, status),
    CONSTRAINT chk_todo_status CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled'))
)
PARTITION BY LIST (status) (
    PARTITION p_active VALUES ('pending', 'in_progress'),
    PARTITION p_done VALUES ('completed', 'cancelled'),
    PARTITION p_other VALUES (DEFAULT) -- Safety net
);

CREATE INDEX idx_todos_user ON todos(user_id) LOCAL;
CREATE INDEX idx_todos_created ON todos(created_at) LOCAL;


-- ==========================================
-- 2. ACTIVITY LOGS TABLE
-- ==========================================
-- Using INTERVAL partitioning - Oracle will create new partitions automatically!
CREATE TABLE activity_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    todo_id NUMBER,
    action VARCHAR2(50) NOT NULL,
    entity_type VARCHAR2(50) NOT NULL,
    details CLOB,
    ip_address VARCHAR2(45),
    user_agent CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT pk_activity_logs PRIMARY KEY (id, created_at)
)
PARTITION BY RANGE (created_at) 
INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION p_old VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')),
    PARTITION p_2023_initial VALUES LESS THAN (TO_DATE('2023-02-01', 'YYYY-MM-DD'))
);

CREATE INDEX idx_logs_user ON activity_logs(user_id) LOCAL;
CREATE INDEX idx_logs_action ON activity_logs(action) LOCAL;
