-- ============================================================================
-- Query Pilot - Oracle Comprehensive Test Schema (E-commerce)
-- ============================================================================
-- Matches PostgreSQL/MySQL/SQL Server schema for consistency
-- ============================================================================

SET SQLBLANKLINES ON;

-- ============================================================================
-- 1. CLEANUP (Drop all objects in reverse dependency order)
-- ============================================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE order_audit_log CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reviews CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE inventory CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE addresses CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE suppliers CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE all_data_types CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE null_patterns CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE unicode_samples CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE numeric_extremes CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE json_documents CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE temporal_data CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE large_table CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE wide_table CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE empty_table CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE single_row_table CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_order_details'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_product_inventory'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW v_customer_summary'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================================
-- 2. CORE ECOMMERCE TABLES
-- ============================================================================

-- Customers table
CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR2(36) DEFAULT REGEXP_REPLACE(RAWTOHEX(SYS_GUID()), '([A-F0-9]{8})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{12})', '\1-\2-\3-\4-\5') NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    date_of_birth DATE,
    gender CHAR(1) CHECK (gender IN ('M', 'F', 'O')),
    is_active NUMBER(1) DEFAULT 1,
    is_verified NUMBER(1) DEFAULT 0,
    loyalty_points NUMBER DEFAULT 0,
    preferences CLOB,
    metadata CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE customers ADD CONSTRAINT ensure_cust_pref_json CHECK (preferences IS JSON);
ALTER TABLE customers ADD CONSTRAINT ensure_cust_meta_json CHECK (metadata IS JSON);

-- email already indexed via UNIQUE constraint
CREATE INDEX idx_customers_name ON customers(last_name, first_name);

-- Addresses table
CREATE TABLE addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    address_type VARCHAR2(20) DEFAULT 'both' CHECK (address_type IN ('billing', 'shipping', 'both')),
    street_line1 VARCHAR2(255) NOT NULL,
    street_line2 VARCHAR2(255),
    city VARCHAR2(100) NOT NULL,
    state VARCHAR2(100),
    postal_code VARCHAR2(20) NOT NULL,
    country CHAR(2) DEFAULT 'US' NOT NULL,
    is_default NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_addresses_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- Categories table (self-referential for hierarchy)
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id NUMBER,
    name VARCHAR2(100) NOT NULL,
    slug VARCHAR2(100) UNIQUE NOT NULL,
    description CLOB,
    image_url VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1,
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Suppliers table
CREATE TABLE suppliers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(255) NOT NULL,
    contact_name VARCHAR2(100),
    contact_email VARCHAR2(255),
    contact_phone VARCHAR2(20),
    address CLOB,
    country CHAR(2),
    is_active NUMBER(1) DEFAULT 1,
    rating NUMBER(3,2) CHECK (rating >= 0 AND rating <= 5),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Products table
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR2(36) DEFAULT REGEXP_REPLACE(RAWTOHEX(SYS_GUID()), '([A-F0-9]{8})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{12})', '\1-\2-\3-\4-\5') NOT NULL,
    sku VARCHAR2(50) UNIQUE NOT NULL,
    name VARCHAR2(255) NOT NULL,
    slug VARCHAR2(255) UNIQUE NOT NULL,
    description CLOB,
    short_description VARCHAR2(500),
    category_id NUMBER,
    supplier_id NUMBER,
    price NUMBER(12,2) NOT NULL CHECK (price >= 0),
    cost_price NUMBER(12,2) CHECK (cost_price >= 0),
    compare_at_price NUMBER(12,2),
    currency CHAR(3) DEFAULT 'USD',
    weight_kg NUMBER(8,3),
    dimensions CLOB,
    is_active NUMBER(1) DEFAULT 1,
    is_featured NUMBER(1) DEFAULT 0,
    is_digital NUMBER(1) DEFAULT 0,
    tax_rate NUMBER(5,2) DEFAULT 0,
    rating_avg NUMBER(3,2) DEFAULT 0,
    rating_count NUMBER DEFAULT 0,
    tags CLOB,
    attributes CLOB,
    images CLOB,
    xml_data XMLTYPE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
);

ALTER TABLE products ADD CONSTRAINT ensure_prod_dims_json CHECK (dimensions IS JSON);
ALTER TABLE products ADD CONSTRAINT ensure_prod_tags_json CHECK (tags IS JSON);
ALTER TABLE products ADD CONSTRAINT ensure_prod_attr_json CHECK (attributes IS JSON);
ALTER TABLE products ADD CONSTRAINT ensure_prod_imgs_json CHECK (images IS JSON);

CREATE INDEX idx_products_category ON products(category_id);
-- sku already indexed via UNIQUE constraint
CREATE INDEX idx_products_price ON products(price);

-- Inventory table
CREATE TABLE inventory (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    warehouse_code VARCHAR2(20) DEFAULT 'MAIN' NOT NULL,
    quantity NUMBER DEFAULT 0 CHECK (quantity >= 0),
    reserved_quantity NUMBER DEFAULT 0 CHECK (reserved_quantity >= 0),
    reorder_level NUMBER DEFAULT 10,
    reorder_quantity NUMBER DEFAULT 50,
    last_restocked_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uk_product_warehouse UNIQUE (product_id, warehouse_code)
);

-- Orders table (Partitioned by created_at)
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    uuid VARCHAR2(36) DEFAULT REGEXP_REPLACE(RAWTOHEX(SYS_GUID()), '([A-F0-9]{8})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{4})([A-F0-9]{12})', '\1-\2-\3-\4-\5') NOT NULL,
    order_number VARCHAR2(20) NOT NULL,
    customer_id NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
    payment_method VARCHAR2(20) CHECK (payment_method IN ('credit_card', 'debit_card', 'paypal', 'bank_transfer', 'cash', 'crypto')),
    payment_status VARCHAR2(20) DEFAULT 'pending',
    shipping_address_id NUMBER,
    billing_address_id NUMBER,
    subtotal NUMBER(12,2) DEFAULT 0,
    tax_amount NUMBER(12,2) DEFAULT 0,
    shipping_amount NUMBER(12,2) DEFAULT 0,
    discount_amount NUMBER(12,2) DEFAULT 0,
    total_amount NUMBER(12,2) DEFAULT 0,
    currency CHAR(3) DEFAULT 'USD',
    notes CLOB,
    metadata CLOB,
    ip_address VARCHAR2(45),
    user_agent CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    shipped_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id, created_at)
)
PARTITION BY RANGE (created_at) (
    PARTITION p_2023 VALUES LESS THAN (TIMESTAMP '2024-01-01 00:00:00'),
    PARTITION p_2024 VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
    PARTITION p_2025 VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'),
    PARTITION p_2026 VALUES LESS THAN (TIMESTAMP '2027-01-01 00:00:00'),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);

ALTER TABLE orders ADD CONSTRAINT ensure_ord_meta_json CHECK (metadata IS JSON);

CREATE INDEX idx_orders_customer ON orders(customer_id) LOCAL;
CREATE INDEX idx_orders_status ON orders(status) LOCAL;
CREATE UNIQUE INDEX idx_orders_number ON orders(order_number);

-- Order Items table
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    order_created_at TIMESTAMP NOT NULL,
    product_id NUMBER NOT NULL,
    product_name VARCHAR2(255) NOT NULL,
    product_sku VARCHAR2(50) NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    unit_price NUMBER(12,2) NOT NULL,
    discount_percent NUMBER(5,2) DEFAULT 0,
    tax_rate NUMBER(5,2) DEFAULT 0,
    total_price NUMBER(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order ON order_items(order_id);

-- Reviews table
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    order_id NUMBER,
    rating NUMBER(1) NOT NULL CHECK (rating >= 1 AND rating <= 5),
    title VARCHAR2(255),
    content CLOB,
    pros CLOB,
    cons CLOB,
    is_verified_purchase NUMBER(1) DEFAULT 0,
    is_approved NUMBER(1) DEFAULT 0,
    helpful_count NUMBER DEFAULT 0,
    images CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT uk_review_prod_cust UNIQUE (product_id, customer_id)
);

ALTER TABLE reviews ADD CONSTRAINT ensure_rev_pros_json CHECK (pros IS JSON);
ALTER TABLE reviews ADD CONSTRAINT ensure_rev_cons_json CHECK (cons IS JSON);
ALTER TABLE reviews ADD CONSTRAINT ensure_rev_imgs_json CHECK (images IS JSON);

-- Order Audit Log table
CREATE TABLE order_audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    action VARCHAR2(20) NOT NULL,
    old_values CLOB,
    new_values CLOB,
    changed_by VARCHAR2(100),
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE order_audit_log ADD CONSTRAINT ensure_audit_old_json CHECK (old_values IS JSON);
ALTER TABLE order_audit_log ADD CONSTRAINT ensure_audit_new_json CHECK (new_values IS JSON);

-- ============================================================================
-- 3. EDGE CASE / DATA TYPE TABLES
-- ============================================================================

-- All Oracle Data Types
CREATE TABLE all_data_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    col_number NUMBER,
    col_number_precision NUMBER(38,10),
    col_binary_float BINARY_FLOAT,
    col_binary_double BINARY_DOUBLE,
    col_char CHAR(100),
    col_varchar2 VARCHAR2(4000),
    col_nchar NCHAR(100),
    col_nvarchar2 NVARCHAR2(2000),
    col_clob CLOB,
    col_nclob NCLOB,
    col_blob BLOB,
    col_raw RAW(2000),
    col_date DATE,
    col_timestamp TIMESTAMP(9),
    col_timestamp_tz TIMESTAMP(9) WITH TIME ZONE,
    col_timestamp_ltz TIMESTAMP(9) WITH LOCAL TIME ZONE,
    col_interval_ym INTERVAL YEAR(4) TO MONTH,
    col_interval_ds INTERVAL DAY(4) TO SECOND(9),
    col_xmltype XMLTYPE,
    col_json CLOB,
    col_rowid ROWID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE all_data_types ADD CONSTRAINT ensure_adt_json CHECK (col_json IS JSON);

-- Null Patterns table
CREATE TABLE null_patterns (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL,
    all_null_row CLOB,
    nullable_int NUMBER,
    nullable_text CLOB,
    nullable_bool NUMBER(1),
    nullable_date DATE,
    nullable_json CLOB,
    default_null CLOB DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Unicode Samples table
CREATE TABLE unicode_samples (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL,
    sample_text NCLOB NOT NULL,
    category VARCHAR2(50) NOT NULL,
    char_count NUMBER,
    byte_count NUMBER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Numeric Extremes table
CREATE TABLE numeric_extremes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL,
    tiny_val NUMBER(3),
    small_val NUMBER(5),
    int_val NUMBER(10),
    big_val NUMBER(19),
    decimal_val NUMBER(38,18),
    float_val BINARY_FLOAT,
    double_val BINARY_DOUBLE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- JSON Documents table
CREATE TABLE json_documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL,
    doc_json CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE json_documents ADD CONSTRAINT ensure_jd_json CHECK (doc_json IS JSON);

-- Temporal Data table
CREATE TABLE temporal_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL,
    date_val DATE,
    timestamp_val TIMESTAMP(6),
    timestamp_tz_val TIMESTAMP(6) WITH TIME ZONE,
    timestamp_ltz_val TIMESTAMP(6) WITH LOCAL TIME ZONE,
    interval_ym_val INTERVAL YEAR TO MONTH,
    interval_ds_val INTERVAL DAY TO SECOND,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 4. SCALE TEST TABLES
-- ============================================================================

-- Large Table
CREATE TABLE large_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    random_int NUMBER,
    random_text VARCHAR2(100),
    random_date DATE,
    random_bool NUMBER(1),
    category VARCHAR2(20),
    amount NUMBER(12,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_large_table_category ON large_table(category);
CREATE INDEX idx_large_table_date ON large_table(random_date);

-- Wide Table (50 columns)
CREATE TABLE wide_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    col_001 VARCHAR2(50), col_002 VARCHAR2(50), col_003 VARCHAR2(50), col_004 VARCHAR2(50), col_005 VARCHAR2(50),
    col_006 VARCHAR2(50), col_007 VARCHAR2(50), col_008 VARCHAR2(50), col_009 VARCHAR2(50), col_010 VARCHAR2(50),
    col_011 NUMBER, col_012 NUMBER, col_013 NUMBER, col_014 NUMBER, col_015 NUMBER,
    col_016 NUMBER, col_017 NUMBER, col_018 NUMBER, col_019 NUMBER, col_020 NUMBER,
    col_021 NUMBER(10,2), col_022 NUMBER(10,2), col_023 NUMBER(10,2), col_024 NUMBER(10,2), col_025 NUMBER(10,2),
    col_026 NUMBER(1), col_027 NUMBER(1), col_028 NUMBER(1), col_029 NUMBER(1), col_030 NUMBER(1),
    col_031 DATE, col_032 DATE, col_033 DATE, col_034 DATE, col_035 DATE,
    col_036 TIMESTAMP, col_037 TIMESTAMP, col_038 TIMESTAMP, col_039 TIMESTAMP, col_040 TIMESTAMP,
    col_041 CLOB, col_042 CLOB, col_043 CLOB, col_044 CLOB, col_045 CLOB,
    col_046 CLOB, col_047 CLOB, col_048 CLOB, col_049 CLOB, col_050 CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Empty Table
CREATE TABLE empty_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    value NUMBER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Single Row Table
CREATE TABLE single_row_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- 5. VIEWS
-- ============================================================================

CREATE VIEW v_order_details AS
SELECT 
    o.id AS order_id,
    o.order_number,
    o.status,
    o.total_amount,
    o.created_at AS order_date,
    c.id AS customer_id,
    c.email AS customer_email,
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(oi.id) AS item_count,
    SUM(oi.quantity) AS total_quantity
FROM orders o
JOIN customers c ON o.customer_id = c.id
LEFT JOIN order_items oi ON o.id = oi.order_id
GROUP BY o.id, o.order_number, o.status, o.total_amount, o.created_at, 
         c.id, c.email, c.first_name, c.last_name;

CREATE VIEW v_product_inventory AS
SELECT 
    p.id AS product_id,
    p.sku,
    p.name AS product_name,
    p.price,
    cat.name AS category_name,
    NVL(SUM(i.quantity), 0) AS total_stock,
    NVL(SUM(i.reserved_quantity), 0) AS reserved_stock,
    NVL(SUM(i.quantity - i.reserved_quantity), 0) AS available_stock,
    p.is_active,
    CASE 
        WHEN NVL(SUM(i.quantity), 0) = 0 THEN 'out_of_stock'
        WHEN NVL(SUM(i.quantity), 0) <= MIN(i.reorder_level) THEN 'low_stock'
        ELSE 'in_stock'
    END AS stock_status
FROM products p
LEFT JOIN categories cat ON p.category_id = cat.id
LEFT JOIN inventory i ON p.id = i.product_id
GROUP BY p.id, p.sku, p.name, p.price, cat.name, p.is_active;

CREATE VIEW v_customer_summary AS
SELECT 
    c.id AS customer_id,
    c.email,
    c.first_name || ' ' || c.last_name AS full_name,
    c.created_at AS member_since,
    COUNT(DISTINCT o.id) AS total_orders,
    NVL(SUM(o.total_amount), 0) AS lifetime_value,
    NVL(AVG(o.total_amount), 0) AS avg_order_value,
    MAX(o.created_at) AS last_order_date,
    c.loyalty_points
FROM customers c
LEFT JOIN orders o ON c.id = o.customer_id AND o.status NOT IN ('cancelled', 'refunded')
GROUP BY c.id, c.email, c.first_name, c.last_name, c.created_at, c.loyalty_points;

-- ============================================================================
-- 6. STORED PROCEDURES AND FUNCTIONS
-- ============================================================================

-- Function: Calculate total order value for a customer
CREATE OR REPLACE FUNCTION fn_customer_lifetime_value(p_customer_id IN NUMBER)
RETURN NUMBER IS
    v_total NUMBER(12,2);
BEGIN
    SELECT NVL(SUM(total_amount), 0) INTO v_total
    FROM orders
    WHERE customer_id = p_customer_id
    AND status NOT IN ('cancelled', 'refunded');
    RETURN v_total;
END;
/

-- Procedure: Update product rating
CREATE OR REPLACE PROCEDURE sp_update_product_rating(p_product_id IN NUMBER) IS
    v_avg_rating NUMBER(3,2);
    v_count NUMBER;
BEGIN
    SELECT NVL(AVG(rating), 0), COUNT(*)
    INTO v_avg_rating, v_count
    FROM reviews
    WHERE product_id = p_product_id AND is_approved = 1;

    UPDATE products
    SET rating_avg = v_avg_rating, rating_count = v_count, updated_at = CURRENT_TIMESTAMP
    WHERE id = p_product_id;
    COMMIT;
END;
/

-- Procedure: Search products by keyword
CREATE OR REPLACE PROCEDURE sp_search_products(
    p_keyword IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cursor FOR
    SELECT id, sku, name, price, rating_avg
    FROM products
    WHERE UPPER(name) LIKE '%' || UPPER(p_keyword) || '%'
    OR UPPER(description) LIKE '%' || UPPER(p_keyword) || '%'
    ORDER BY rating_avg DESC;
END;
/

-- Trigger: Audit order status changes
CREATE OR REPLACE TRIGGER trg_order_status_audit
AFTER UPDATE OF status ON orders
FOR EACH ROW
BEGIN
    INSERT INTO order_audit_log (order_id, action, old_values, new_values, changed_by)
    VALUES (
        :NEW.id,
        'status_change',
        '{"status": "' || :OLD.status || '"}',
        '{"status": "' || :NEW.status || '"}',
        SYS_CONTEXT('USERENV', 'SESSION_USER')
    );
END;
/
