import React, {
  useState,
  useCallback,
  useMemo,
  useRef,
  useEffect,
} from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import {
  GridCellKind,
  type Item,
  type CustomRenderer,
  type GridCell,
  type GridMouseEventArgs,
} from "@glideapps/glide-data-grid";
import { DataGridBase } from "@/components/DataGrid/base/DataGridBase";
import { useColumnSizing, EMPTY_INITIAL_WIDTHS, NOOP_ON_CHANGE } from "@/components/DataGrid/hooks/useColumnSizing";
import type { GridColumnV2 } from "@/components/DataGrid/types";
import ColumnNameCellRenderer from "@/components/TableStructure/ColumnNameCellRenderer";
import { NullableCellRenderer } from "@/components/TableStructure/NullableCellRenderer";
import { DataTypeCellRenderer } from "@/components/TableStructure/DataTypeCellRenderer";
import DefaultValueCellRenderer from "@/components/TableStructure/DefaultValueCellRenderer";
import ForeignKeyCellRenderer from "@/components/TableStructure/ForeignKeyCellRenderer";
import CheckConstraintCellRenderer from "@/components/TableStructure/CheckConstraintCellRenderer";
import CommentCellRenderer from "@/components/TableStructure/CommentCellRenderer";
import { useCrudStore, buildCrudTableKey } from "@/stores/crudStore";
import { createTableCreateCommand } from "./commandFactory";
import type {
  CrudCommand,
  CrudCommandTarget,
  ColumnDefinitionInput,
  ForeignKeyAddPayload,
  IndexCreatePayload,
  TableCreatePayload,
} from "@/types/crud";
import { GlobalChangesDialog } from "@/components/GlobalChangesDialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { IndexDesigner } from "./IndexDesigner";
import { toast } from "sonner";
import { useForeignKeyTargets } from "@/hooks/useForeignKeyTargets";
import { useSupportedColumnTypes } from "@/hooks/useSupportedColumnTypes";
import { CrudCommandFactory } from "@/services/crudCommandFactory";
import useWorkbenchStore from "@/stores/workbenchStore";
import {
  getDesignerModifiedFields,
  syncIndexCommandsWithColumns,
  type DesignerGridRow,
  type DesignerModifiedField,
} from "./utils";
import { DesignerColumnContextMenu } from "./DesignerColumnContextMenu";
import { DbType, getDefaultSchema, isMySQLCompatible } from "@/types/connection";
import { useConnectionStore } from "@/stores/connectionStoreNew";
import {
  quoteIdentifier as quoteId,
  formatTableName,
} from "@/adapters/formatting";

// ---------------------------------------------------------------------------
// Dialect-specific defaults for new tables
// ---------------------------------------------------------------------------

const DESIGNER_DEFAULTS: Record<string, {
  pkType: string;
  pkName: string;
}> = {
  [DbType.PostgreSQL]: { pkType: "SERIAL", pkName: "id" },
  [DbType.MySQL]:      { pkType: "INT AUTO_INCREMENT", pkName: "id" },
  [DbType.MariaDB]:    { pkType: "INT AUTO_INCREMENT", pkName: "id" },
  [DbType.SQLite]:     { pkType: "INTEGER", pkName: "id" },
  [DbType.SQLServer]:  { pkType: "INT IDENTITY(1,1)", pkName: "id" },
  [DbType.Oracle]:     { pkType: "NUMBER GENERATED BY DEFAULT AS IDENTITY", pkName: "id" },
};

/**
 * Check if a column type implies auto-increment / serial behavior.
 */
const isAutoIncrementType = (type: string, db: DbType): boolean => {
  const upper = type.toUpperCase();
  switch (db) {
    case DbType.PostgreSQL: return upper.includes("SERIAL");
    case DbType.MySQL:
    case DbType.MariaDB: return upper.includes("AUTO_INCREMENT");
    case DbType.SQLServer: return upper.includes("IDENTITY");
    case DbType.Oracle: return upper.includes("IDENTITY");
    default: return false;
  }
};

export interface TableDesignerProps {
  panelId: string;
  tabId: string;
  connectionId: string;
  database: string;
  schema?: string;
  dbType?: DbType;
  className?: string;
  onSave?: (tableName: string, sql: string) => void;
  onCancel?: () => void;
}

const createDefaultColumnDefinition = (): ColumnDefinitionInput => ({
  name: "",
  dataType: "VARCHAR(255)",
  nullable: true,
  defaultValue: undefined,
  isPrimaryKey: false,
});

const normalizeCheckConstraint = (value: string | null): string => {
  if (!value) return "";
  const trimmed = value.trim();
  const match = trimmed.match(/^CHECK\s*\((.*)\)$/is);
  if (match && match[1]) {
    return match[1].trim();
  }
  return trimmed;
};

const sanitizeIdentifier = (value: string): string =>
  value.replace(/[^a-zA-Z0-9_]+/g, "_").replace(/^_+|_+$/g, "");

const buildForeignKeyConstraintName = (
  tableName: string,
  columnName: string,
  refTable: string,
  refColumn: string,
): string =>
  sanitizeIdentifier(`fk_${tableName}_${columnName}_${refTable}_${refColumn}`);

const parseForeignKeyValue = (
  rawValue: string,
): { schema?: string; table: string; column: string } | null => {
  const parts = rawValue
    .split(".")
    .map((part) => part.trim())
    .filter(Boolean);
  if (parts.length < 2) return null;
  const column = parts.pop();
  const table = parts.pop();
  if (!column || !table) return null;
  const schema = parts.length ? parts.join(".") : undefined;
  return { schema, table, column };
};

const normalizeDefaultValue = (value: unknown): string => {
  if (value === null || value === undefined) return "";
  return typeof value === "string" ? value : String(value);
};

const buildForeignKeyValue = (payload: ForeignKeyAddPayload): string => {
  const definition = payload.definition;
  if (!definition?.columns?.length || !definition.referenceTable) return "";
  const referenceColumn = definition.referenceColumns?.[0];
  if (!referenceColumn) return "";
  const refTable = definition.referenceSchema
    ? `${definition.referenceSchema}.${definition.referenceTable}`
    : definition.referenceTable;
  return `${refTable}.${referenceColumn}`;
};

const ensureTags = (tags: string[] | undefined, next: string[]): string[] =>
  Array.from(new Set([...(tags ?? []), ...next])).filter(Boolean);

const buildFkTag = (prefix: string, index: number): string =>
  `${prefix}${index}`;

const getFkIndexFromTags = (
  tags: string[] | undefined,
  prefix: string,
): number | null => {
  const tag = tags?.find((item) => item.startsWith(prefix));
  if (!tag) return null;
  const index = Number.parseInt(tag.slice(prefix.length), 10);
  return Number.isNaN(index) ? null : index;
};

const resolveTableName = (value: string, fallback: string): string =>
  value.trim() || fallback;

const getCommandTimestamp = (command: CrudCommand): number => {
  const raw = command.metadata.timestamp;
  const timestamp = raw ? Date.parse(raw) : Number.NaN;
  return Number.isNaN(timestamp) ? 0 : timestamp;
};

const trailingRowTheme = {
  bgIconHeader: "#D4A52B",
};

const trailingRowOptions = {
  hint: " ",
  themeOverride: trailingRowTheme,
};

// Designer columns
const designerColumns: GridColumnV2[] = [
  {
    id: "row_number",
    field: "row_number",
    title: "#",
    name: "#",
    width: 48,
    minWidth: 48,
    maxWidth: 80,
    trailingRowOptions,
  },
  {
    id: "column_name",
    field: "column_name",
    title: "Column",
    name: "Column",
    width: 200,
    minWidth: 120,
    maxWidth: 400,
  },
  {
    id: "db_type",
    field: "db_type",
    title: "Type",
    name: "Type",
    width: 180,
    minWidth: 100,
    maxWidth: 300,
  },
  {
    id: "nullable",
    field: "nullable",
    title: "Nullable",
    name: "Nullable",
    width: 100,
    minWidth: 80,
    maxWidth: 120,
  },
  {
    id: "default",
    field: "default",
    title: "Default",
    name: "Default",
    width: 160,
    minWidth: 100,
    maxWidth: 300,
  },
  {
    id: "foreign_key",
    field: "foreign_key",
    title: "Foreign Key",
    name: "Foreign Key",
    width: 200,
    minWidth: 140,
    maxWidth: 400,
  },
  {
    id: "check_constraint",
    field: "check_constraint",
    title: "Check",
    name: "Check",
    width: 200,
    minWidth: 140,
  },
  {
    id: "comment",
    field: "comment",
    title: "Comment",
    name: "Comment",
    width: 240,
    minWidth: 140,
  },
];

export const TableDesigner: React.FC<TableDesignerProps> = ({
  panelId,
  tabId,
  connectionId,
  database,
  schema,
  dbType,
  className,
  onSave,
  onCancel,
}) => {
  const connection = useConnectionStore((s) => s.getConnection(connectionId));
  const resolvedDbType = dbType ?? connection?.profile.db_type ?? DbType.PostgreSQL;
  const resolvedSchema = schema ?? getDefaultSchema(resolvedDbType, database) ?? undefined;

  const { columnTypes } = useSupportedColumnTypes({
    connectionId,
    dbType: resolvedDbType,
  });

  const tableNameInputRef = useRef<HTMLInputElement>(null);
  const [globalChangesDialogOpen, setGlobalChangesDialogOpen] = useState(false);
  const [tableNameDraft, setTableNameDraft] = useState("");
  const updateTabMetadata = useWorkbenchStore((s) => s.updateTabMetadata);
  const stagedCommands = useCrudStore((state) => state.stagedCommands);
  const stageBatchWithSingleHistoryEntry = useCrudStore(
    (state) => state.stageBatchWithSingleHistoryEntry,
  );
  const unstageCommands = useCrudStore((state) => state.unstageCommands);
  const discardChanges = useCrudStore((state) => state.discardChanges);
  const { targets: foreignKeyTargets } = useForeignKeyTargets({
    connectionId,
    database,
    schema: resolvedSchema,
  });

  const designerTag = useMemo(
    () => `table-designer:${panelId}:${tabId}`,
    [panelId, tabId],
  );
  const fkTagPrefix = useMemo(
    () => `table-designer-fk:${panelId}:${tabId}:`,
    [panelId, tabId],
  );
  const draftTableName = useMemo(() => `__new_table_${tabId}`, [tabId]);

  const designerCommands = useMemo(() => {
    const commands: CrudCommand[] = [];
    stagedCommands.forEach((items) => {
      items.forEach((command) => {
        if (command.metadata.tags?.includes(designerTag)) {
          commands.push(command);
        }
      });
    });
    return commands;
  }, [designerTag, stagedCommands]);

  const tableCreateCommands = useMemo(
    () => designerCommands.filter((cmd) => cmd.type === "table.create"),
    [designerCommands],
  );

  const tableCreateCommand = useMemo(() => {
    if (tableCreateCommands.length === 0) return undefined;
    return [...tableCreateCommands].sort(
      (a, b) => getCommandTimestamp(b) - getCommandTimestamp(a),
    )[0];
  }, [tableCreateCommands]);

  const fkCommands = useMemo(
    () => designerCommands.filter((cmd) => cmd.type === "fk.add"),
    [designerCommands],
  );

  const tableName =
    (tableCreateCommand?.payload as TableCreatePayload | undefined)
      ?.tableName ?? "";
  const tableTargetName = tableCreateCommand?.target.table ?? draftTableName;
  const effectiveTableName = tableNameDraft.trim() || tableName.trim();

  // Auto-focus on table name input
  useEffect(() => {
    tableNameInputRef.current?.focus();
  }, []);

  // Sync table name draft when staged value changes from external source (e.g., undo/redo)
  useEffect(() => {
    setTableNameDraft(tableName);
  }, [tableName]);

  useEffect(() => {
    if (tableCreateCommands.length <= 1) return;
    const sorted = [...tableCreateCommands].sort(
      (a, b) => getCommandTimestamp(b) - getCommandTimestamp(a),
    );
    const canonical = sorted[0];
    if (!canonical) return;

    const duplicateIds = tableCreateCommands
      .filter((cmd) => cmd.id !== canonical.id)
      .map((cmd) => cmd.id);
    if (duplicateIds.length > 0) {
      unstageCommands(duplicateIds);
    }
  }, [tableCreateCommands, unstageCommands]);

  const buildDesignerCreateCommand = useCallback(
    (
      target: CrudCommandTarget,
      payload: {
        tableName: string;
        columns: ColumnDefinitionInput[];
        primaryKey?: string[];
        ifNotExists?: boolean;
      },
    ) => {
      const createCommand = createTableCreateCommand(target, payload);
      return {
        ...createCommand,
        // Stable ID keeps initialization idempotent under StrictMode/effect replay.
        id: `${designerTag}:table.create`,
        metadata: {
          ...createCommand.metadata,
          tags: ensureTags(createCommand.metadata.tags, [designerTag]),
        },
      };
    },
    [designerTag],
  );

  useEffect(() => {
    if (!connectionId || !database || tableCreateCommand) return;

    const target: CrudCommandTarget = {
      connectionId,
      database,
      schema: resolvedSchema,
      table: draftTableName,
    };

    const defaults = DESIGNER_DEFAULTS[resolvedDbType] ?? { pkType: "SERIAL", pkName: "id" };
    const defaultColumns = [
      {
        name: defaults.pkName,
        dataType: defaults.pkType,
        nullable: false,
        defaultValue: undefined,
        isPrimaryKey: true,
      },
    ] satisfies ColumnDefinitionInput[];

    const createCommand = buildDesignerCreateCommand(target, {
      tableName: "",
      columns: defaultColumns,
      primaryKey: ["id"],
    });

    stageBatchWithSingleHistoryEntry([createCommand]);
  }, [
    buildDesignerCreateCommand,
    connectionId,
    database,
    draftTableName,
    resolvedDbType,
    resolvedSchema,
    stageBatchWithSingleHistoryEntry,
    tableCreateCommand,
  ]);

  const columns = useMemo(
    () =>
      (tableCreateCommand?.payload as TableCreatePayload | undefined)
        ?.columns ?? [],
    [tableCreateCommand],
  );

  const baselineColumnsRef = useRef<ColumnDefinitionInput[]>([]);

  useEffect(() => {
    if (columns.length === 0) {
      return;
    }

    if (baselineColumnsRef.current.length === 0) {
      baselineColumnsRef.current = columns.map((col) => ({ ...col }));
      return;
    }

    if (columns.length > baselineColumnsRef.current.length) {
      for (
        let i = baselineColumnsRef.current.length;
        i < columns.length;
        i += 1
      ) {
        baselineColumnsRef.current[i] = createDefaultColumnDefinition();
      }
    } else if (columns.length < baselineColumnsRef.current.length) {
      baselineColumnsRef.current = baselineColumnsRef.current.slice(
        0,
        columns.length,
      );
    }
  }, [columns]);

  const primaryKeySet = useMemo(
    () =>
      new Set(
        (tableCreateCommand?.payload as TableCreatePayload | undefined)
          ?.primaryKey ?? [],
      ),
    [tableCreateCommand],
  );

  const foreignKeyByIndex = useMemo(() => {
    const map = new Map<number, string>();
    fkCommands.forEach((cmd) => {
      const index = getFkIndexFromTags(cmd.metadata.tags, fkTagPrefix);
      if (index === null) return;
      const value = buildForeignKeyValue(cmd.payload as ForeignKeyAddPayload);
      if (value) {
        map.set(index, value);
      }
    });
    return map;
  }, [fkCommands, fkTagPrefix]);

  const foreignKeyByColumnName = useMemo(() => {
    const map = new Map<string, string>();
    fkCommands.forEach((cmd) => {
      const payload = cmd.payload as ForeignKeyAddPayload;
      const columnName = payload.definition?.columns?.[0];
      if (!columnName) return;
      const value = buildForeignKeyValue(payload);
      if (value) {
        map.set(columnName, value);
      }
    });
    return map;
  }, [fkCommands]);

  const gridRows = useMemo((): DesignerGridRow[] => {
    return columns.map((col, index) => {
      const columnName = col.name ?? "";
      const isPrimaryKey =
        Boolean(col.isPrimaryKey) ||
        primaryKeySet.has(columnName) ||
        isAutoIncrementType(col.dataType ?? "", resolvedDbType);
      const fkValue =
        foreignKeyByIndex.get(index) ||
        (columnName ? foreignKeyByColumnName.get(columnName) : "") ||
        "";

      return {
        row_number: index + 1,
        column_name: columnName,
        column_meta: {
          is_pk: isPrimaryKey,
          is_fk: Boolean(fkValue),
        },
        db_type: col.dataType || "VARCHAR(255)",
        nullable: !col.nullable ? "NO" : "YES",
        default: normalizeDefaultValue(col.defaultValue),
        foreign_key: fkValue,
        check_constraint: col.checkExpression ?? "",
        comment: col.comment ?? "",
        _tempId: `${index}`,
      };
    });
  }, [columns, foreignKeyByColumnName, foreignKeyByIndex, primaryKeySet, resolvedDbType]);

  // Column names for IndexDesigner's column picker
  const availableColumnNames = useMemo(
    () => columns.filter((c) => c.name.trim()).map((c) => c.name),
    [columns],
  );

  // FK column names for auto-suggest
  const foreignKeyColumnNames = useMemo(() => {
    const fkCols: string[] = [];
    fkCommands.forEach((cmd) => {
      const payload = cmd.payload as ForeignKeyAddPayload;
      const colName = payload.definition?.columns?.[0];
      if (colName) fkCols.push(colName);
    });
    return fkCols;
  }, [fkCommands]);

  // Count index commands for tab badge
  const indexCommandCount = useMemo(
    () => designerCommands.filter((cmd) => cmd.type === "index.create").length,
    [designerCommands],
  );

  // Track previous column names for rename detection
  const prevColumnNamesRef = useRef<string[]>([]);

  useEffect(() => {
    const currentNames = availableColumnNames;
    const prevNames = prevColumnNamesRef.current;
    prevColumnNamesRef.current = currentNames;

    // Skip first render or when no index commands
    if (prevNames.length === 0 || indexCommandCount === 0) return;

    // Build rename map: detect 1:1 positional renames
    const renames = new Map<string, string>();
    const minLen = Math.min(prevNames.length, currentNames.length);
    for (let i = 0; i < minLen; i++) {
      if (prevNames[i] && currentNames[i] && prevNames[i] !== currentNames[i]) {
        // Only treat as rename if old name no longer exists anywhere
        if (!currentNames.includes(prevNames[i]!)) {
          renames.set(prevNames[i]!, currentNames[i]!);
        }
      }
    }

    // Get current index commands from designerCommands
    const currentIndexCommands = designerCommands.filter(
      (cmd) => cmd.type === "index.create",
    );

    if (currentIndexCommands.length === 0) return;

    const synced = syncIndexCommandsWithColumns(
      currentIndexCommands,
      currentNames,
      renames,
    );

    if (!synced) return;

    // Find removed command IDs (commands excluded from synced result)
    const syncedIds = new Set(synced.map((c) => c.id));
    const removedIds = currentIndexCommands
      .filter((c) => !syncedIds.has(c.id))
      .map((c) => c.id);

    if (removedIds.length > 0) {
      unstageCommands(removedIds);
    }

    // Stage only commands that actually changed
    const updatedCommands = synced.filter((c) => {
      const original = currentIndexCommands.find((orig) => orig.id === c.id);
      return original !== c; // reference equality — changed commands are new objects
    });

    if (updatedCommands.length > 0) {
      stageBatchWithSingleHistoryEntry(updatedCommands);
    }
  }, [
    availableColumnNames,
    designerCommands,
    indexCommandCount,
    stageBatchWithSingleHistoryEntry,
    unstageCommands,
  ]);

  const fkCommandByIndex = useMemo(() => {
    const map = new Map<number, CrudCommand>();
    fkCommands.forEach((cmd) => {
      const index = getFkIndexFromTags(cmd.metadata.tags, fkTagPrefix);
      if (index === null) return;
      map.set(index, cmd);
    });
    return map;
  }, [fkCommands, fkTagPrefix]);

  const fkCommandByColumnName = useMemo(() => {
    const map = new Map<string, CrudCommand>();
    fkCommands.forEach((cmd) => {
      const payload = cmd.payload as ForeignKeyAddPayload;
      const columnName = payload.definition?.columns?.[0];
      if (!columnName) return;
      map.set(columnName, cmd);
    });
    return map;
  }, [fkCommands]);

  const resolveTargetTableName = useCallback(
    (nextTableName: string) => resolveTableName(nextTableName, draftTableName),
    [draftTableName],
  );

  const buildTableCreateCommand = useCallback(
    (nextColumns: ColumnDefinitionInput[], nextTableName: string) => {
      if (!tableCreateCommand) return null;

      const trimmedName = nextTableName.trim();
      const primaryKey = nextColumns
        .filter((col) => col.isPrimaryKey && col.name)
        .map((col) => col.name);

      const payload = {
        ...(tableCreateCommand.payload as TableCreatePayload),
        tableName: trimmedName,
        columns: nextColumns,
        primaryKey: primaryKey.length > 0 ? primaryKey : undefined,
      };

      return {
        ...tableCreateCommand,
        target: {
          ...tableCreateCommand.target,
          table: resolveTargetTableName(trimmedName),
        },
        payload,
        metadata: {
          ...tableCreateCommand.metadata,
          description: `Create table ${trimmedName || "New Table"}`,
          tags: ensureTags(tableCreateCommand.metadata.tags, [designerTag]),
        },
      };
    },
    [designerTag, resolveTargetTableName, tableCreateCommand],
  );

  const buildForeignKeyCommand = useCallback(
    (
      index: number,
      value: string,
      columnName: string,
      currentCommand?: CrudCommand,
      nextTableName?: string,
    ) => {
      const resolvedNextTableName = nextTableName ?? tableName;
      if (!tableCreateCommand) return null;
      if (!columnName) return null;

      const parsed = parseForeignKeyValue(value);
      if (!parsed) return { error: "invalid" } as const;

      const trimmedTableName = resolvedNextTableName.trim();
      const resolvedTableName = resolveTargetTableName(
        trimmedTableName || resolvedNextTableName,
      );
      const constraintName = buildForeignKeyConstraintName(
        trimmedTableName || resolvedTableName,
        columnName,
        parsed.table,
        parsed.column,
      );
      const definition = {
        name: constraintName,
        columns: [columnName],
        referenceTable: parsed.table,
        referenceSchema: parsed.schema,
        referenceColumns: [parsed.column],
      };

      const baseCommand =
        currentCommand ??
        CrudCommandFactory.createForeignKeyAddCommand({
          target: {
            ...tableCreateCommand.target,
            table: resolvedTableName,
          },
          definition,
        });

      const fkTag = buildFkTag(fkTagPrefix, index);
      return {
        ...baseCommand,
        id: currentCommand?.id ?? `${tableCreateCommand.id}:fk:${index}`,
        target: {
          ...baseCommand.target,
          table: resolvedTableName,
        },
        payload: {
          ...(baseCommand.payload as ForeignKeyAddPayload),
          definition,
        },
        metadata: {
          ...baseCommand.metadata,
          tags: ensureTags(baseCommand.metadata.tags, [designerTag, fkTag]),
        },
      };
    },
    [
      designerTag,
      fkTagPrefix,
      resolveTargetTableName,
      tableCreateCommand,
      tableName,
    ],
  );

  // Column sizing
  const { sizedColumns, handleColumnResize, handleColumnResizeEnd } =
    useColumnSizing({
      columns: designerColumns,
      initialWidths: EMPTY_INITIAL_WIDTHS,
      onChange: NOOP_ON_CHANGE,
    });

  // Custom renderers
  const customRenderers = useMemo(
    () => [
      ColumnNameCellRenderer as unknown as CustomRenderer,
      DefaultValueCellRenderer as unknown as CustomRenderer,
      ForeignKeyCellRenderer as unknown as CustomRenderer,
      CheckConstraintCellRenderer as unknown as CustomRenderer,
      CommentCellRenderer as unknown as CustomRenderer,
      NullableCellRenderer as unknown as CustomRenderer,
      DataTypeCellRenderer as unknown as CustomRenderer,
    ],
    [],
  );

  // Get cell content
  const getCellContent = useCallback(
    ([col, row]: Item): GridCell => {
      const rowData = gridRows[row];
      if (!rowData) {
        return {
          kind: GridCellKind.Text,
          data: "",
          displayData: "",
          allowOverlay: false,
        };
      }

      const column = sizedColumns[col];
      const field = column?.field;
      const baseline = baselineColumnsRef.current[row];
      const modifiedFields = getDesignerModifiedFields(rowData, baseline);
      const isCellModified = Boolean(
        field && modifiedFields.has(field as DesignerModifiedField),
      );
      const cellThemeOverride = isCellModified
        ? {
            bgCell: "rgba(251, 146, 60, 0.15)", // orange highlight
            accentColor: "#fb923c",
            accentLight: "rgba(251, 146, 60, 0.2)",
          }
        : undefined;

      switch (field) {
        case "row_number":
          return {
            kind: GridCellKind.Number,
            data: rowData.row_number,
            displayData: String(rowData.row_number),
            allowOverlay: false,
            readonly: true,
          };

        case "column_name":
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "column-name-cell",
              name: rowData.column_name || "",
              isPrimaryKey: rowData.column_meta.is_pk,
              isForeignKey: rowData.column_meta.is_fk,
            },
            copyData: rowData.column_name || "",
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };

        case "db_type":
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "datatype-cell",
              value: rowData.db_type,
              standardTypes: columnTypes,
              columnName: rowData.column_name,
            },
            copyData: rowData.db_type,
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };

        case "nullable":
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "nullable-cell",
              value: rowData.nullable,
              columnName: rowData.column_name,
            },
            copyData: rowData.nullable,
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };

        case "default":
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "default-value-cell",
              value: rowData.default?.trim() ? rowData.default : null,
              columnName: rowData.column_name,
              dbType: rowData.db_type,
            },
            copyData: rowData.default?.trim() ? rowData.default : "NULL",
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };

        case "foreign_key":
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "foreign-key-cell",
              value: rowData.foreign_key || "",
              suggestions: foreignKeyTargets,
              columnName: rowData.column_name,
            },
            copyData: rowData.foreign_key || "",
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };

        case "check_constraint": {
          const normalizedValue = normalizeCheckConstraint(
            rowData.check_constraint,
          );
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "check-constraint-cell",
              value: normalizedValue || null,
              columnName: rowData.column_name,
            },
            copyData: normalizedValue,
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };
        }

        case "comment":
          return {
            kind: GridCellKind.Custom,
            data: {
              kind: "comment-cell",
              value: rowData.comment || null,
              columnName: rowData.column_name,
            },
            copyData: rowData.comment || "",
            allowOverlay: true,
            themeOverride: cellThemeOverride,
          };

        default:
          return {
            kind: GridCellKind.Text,
            data: "",
            displayData: "",
            allowOverlay: false,
          };
      }
    },
    [gridRows, sizedColumns, foreignKeyTargets, columnTypes],
  );

  // Handle cell edit
  const handleCellEdited = useCallback(
    ([col, row]: Item, newValue: GridCell) => {
      if (!tableCreateCommand) return;

      const column = sizedColumns[col];
      const field = column?.field;
      const current = columns[row];

      if (!field || !current) return;

      const nextColumns = [...columns];
      const updated = { ...current };
      const commands: CrudCommand[] = [];

      const getStringValue = (): string => {
        if (newValue.kind === GridCellKind.Custom) {
          const data = newValue.data as { name?: string; value?: string };
          return data.name || data.value || "";
        }
        if (newValue.kind === GridCellKind.Text) {
          return newValue.data || "";
        }
        return "";
      };

      if (field === "foreign_key") {
        const newForeignKey = getStringValue().trim();
        const existingFkCommand =
          fkCommandByIndex.get(row) ||
          (current.name ? fkCommandByColumnName.get(current.name) : undefined);

        if (!newForeignKey) {
          if (existingFkCommand) {
            unstageCommands([existingFkCommand.id]);
          }
          return;
        }

        if (!current.name) {
          toast.error("Set a column name before adding a foreign key");
          return;
        }

        const fkCommand = buildForeignKeyCommand(
          row,
          newForeignKey,
          current.name,
          existingFkCommand,
        );

        if (fkCommand && "error" in fkCommand) {
          toast.error("Invalid foreign key format", {
            description: "Use table.column or schema.table.column",
          });
          return;
        }

        if (fkCommand) {
          commands.push(fkCommand as CrudCommand);
        }

        if (commands.length > 0) {
          stageBatchWithSingleHistoryEntry(commands);
        }
        return;
      }

      switch (field) {
        case "column_name": {
          const nextName = getStringValue();
          updated.name = nextName;
          nextColumns[row] = updated;

          const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
          const existingFkValue =
            foreignKeyByIndex.get(row) ||
            (current.name
              ? foreignKeyByColumnName.get(current.name)
              : undefined);
          const existingFkCommand =
            fkCommandByIndex.get(row) ||
            (current.name
              ? fkCommandByColumnName.get(current.name)
              : undefined);

          if (existingFkCommand) {
            if (!nextName.trim() || !existingFkValue) {
              unstageCommands([existingFkCommand.id]);
            } else {
              const fkCommand = buildForeignKeyCommand(
                row,
                existingFkValue,
                nextName,
                existingFkCommand,
              );
              if (fkCommand && !("error" in fkCommand)) {
                commands.push(fkCommand as CrudCommand);
              }
            }
          }

          if (updatedCreate) {
            commands.unshift(updatedCreate);
          }
          break;
        }

        case "db_type": {
          const nextType = getStringValue() || "VARCHAR(255)";
          updated.dataType = nextType;
          updated.isPrimaryKey = isAutoIncrementType(nextType, resolvedDbType);
          break;
        }

        case "nullable":
          if (newValue.kind === GridCellKind.Custom) {
            const data = newValue.data as { value?: string };
            updated.nullable = data.value === "YES";
          }
          break;

        case "default": {
          if (newValue.kind === GridCellKind.Custom) {
            const data = newValue.data as { value?: string | null };
            const rawValue = data.value ?? "";
            updated.defaultValue = rawValue.trim() ? rawValue : undefined;
          } else if (newValue.kind === GridCellKind.Text) {
            const rawValue = newValue.data || "";
            updated.defaultValue = rawValue.trim() ? rawValue : undefined;
          }
          break;
        }

        case "check_constraint": {
          if (newValue.kind === GridCellKind.Custom) {
            const data = newValue.data as { value?: string | null };
            const rawValue = data.value ?? "";
            updated.checkExpression = rawValue.trim()
              ? normalizeCheckConstraint(rawValue)
              : undefined;
          } else if (newValue.kind === GridCellKind.Text) {
            const rawValue = newValue.data || "";
            updated.checkExpression = rawValue.trim()
              ? normalizeCheckConstraint(rawValue)
              : undefined;
          }
          break;
        }

        case "comment": {
          if (newValue.kind === GridCellKind.Custom) {
            const data = newValue.data as { value?: string | null };
            const rawValue = data.value ?? "";
            updated.comment = rawValue.trim() ? rawValue : undefined;
          } else if (newValue.kind === GridCellKind.Text) {
            const rawValue = newValue.data || "";
            updated.comment = rawValue.trim() ? rawValue : undefined;
          }
          break;
        }
      }

      if (field !== "column_name") {
        nextColumns[row] = updated;
        const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
        if (updatedCreate) {
          commands.push(updatedCreate);
        }
      }

      if (commands.length > 0) {
        stageBatchWithSingleHistoryEntry(commands);
      }
    },
    [
      buildForeignKeyCommand,
      buildTableCreateCommand,
      columns,
      fkCommandByColumnName,
      fkCommandByIndex,
      foreignKeyByColumnName,
      foreignKeyByIndex,
      resolvedDbType,
      stageBatchWithSingleHistoryEntry,
      tableCreateCommand,
      tableName,
      unstageCommands,
      sizedColumns,
    ],
  );

  // Handle row append
  const handleRowAppended = useCallback(() => {
    if (!tableCreateCommand) return;
    const nextColumns = [...columns, createDefaultColumnDefinition()];
    const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
    if (updatedCreate) {
      stageBatchWithSingleHistoryEntry([updatedCreate]);
    }
  }, [
    buildTableCreateCommand,
    columns,
    stageBatchWithSingleHistoryEntry,
    tableCreateCommand,
    tableName,
  ]);

  // ---- Context menu -------------------------------------------------------
  const contextMenuRowRef = useRef<DesignerGridRow | null>(null);

  const handleItemHovered = useCallback(
    (args: GridMouseEventArgs) => {
      if (args.kind === "cell") {
        contextMenuRowRef.current = gridRows[args.location[1]] ?? null;
      } else {
        contextMenuRowRef.current = null;
      }
    },
    [gridRows],
  );

  const handleContextDuplicate = useCallback(
    (row: DesignerGridRow) => {
      if (!tableCreateCommand) return;
      const rowIndex = Number.parseInt(row._tempId, 10);
      const current = columns[rowIndex];
      if (!current) return;

      const duplicate: ColumnDefinitionInput = {
        ...current,
        name: current.name ? `${current.name}_copy` : "",
        isPrimaryKey: false,
      };

      const nextColumns = [...columns];
      nextColumns.splice(rowIndex + 1, 0, duplicate);
      const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
      if (updatedCreate) {
        stageBatchWithSingleHistoryEntry([updatedCreate]);
      }
    },
    [
      columns,
      buildTableCreateCommand,
      tableName,
      stageBatchWithSingleHistoryEntry,
      tableCreateCommand,
    ],
  );

  const handleContextTogglePK = useCallback(
    (row: DesignerGridRow) => {
      if (!tableCreateCommand) return;
      const rowIndex = Number.parseInt(row._tempId, 10);
      const current = columns[rowIndex];
      if (!current) return;

      const nextColumns = [...columns];
      nextColumns[rowIndex] = {
        ...current,
        isPrimaryKey: !row.column_meta.is_pk,
      };
      const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
      if (updatedCreate) {
        stageBatchWithSingleHistoryEntry([updatedCreate]);
      }
    },
    [
      columns,
      buildTableCreateCommand,
      tableName,
      stageBatchWithSingleHistoryEntry,
      tableCreateCommand,
    ],
  );

  const handleContextSetNullable = useCallback(
    (row: DesignerGridRow, value: "YES" | "NO") => {
      if (!tableCreateCommand) return;
      if (row.nullable === value) return;

      const rowIndex = Number.parseInt(row._tempId, 10);
      const current = columns[rowIndex];
      if (!current) return;

      const nextColumns = [...columns];
      nextColumns[rowIndex] = { ...current, nullable: value === "YES" };
      const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
      if (updatedCreate) {
        stageBatchWithSingleHistoryEntry([updatedCreate]);
      }
    },
    [
      columns,
      buildTableCreateCommand,
      tableName,
      stageBatchWithSingleHistoryEntry,
      tableCreateCommand,
    ],
  );

  const handleContextDeleteColumn = useCallback(
    (row: DesignerGridRow) => {
      if (!tableCreateCommand) return;
      const rowIndex = Number.parseInt(row._tempId, 10);

      // Clean up any associated FK command
      const existingFkCommand =
        fkCommandByIndex.get(rowIndex) ||
        (columns[rowIndex]?.name
          ? fkCommandByColumnName.get(columns[rowIndex].name)
          : undefined);
      if (existingFkCommand) {
        unstageCommands([existingFkCommand.id]);
      }

      const nextColumns = columns.filter((_, i) => i !== rowIndex);
      const updatedCreate = buildTableCreateCommand(nextColumns, tableName);
      if (updatedCreate) {
        stageBatchWithSingleHistoryEntry([updatedCreate]);
      }
    },
    [
      columns,
      buildTableCreateCommand,
      fkCommandByColumnName,
      fkCommandByIndex,
      tableName,
      stageBatchWithSingleHistoryEntry,
      tableCreateCommand,
      unstageCommands,
    ],
  );

  const handleTableNameChange = useCallback(
    (nextName: string) => {
      if (!tableCreateCommand) {
        if (!connectionId || !database) return;

        const target: CrudCommandTarget = {
          connectionId,
          database,
          schema: resolvedSchema,
          table: resolveTargetTableName(nextName),
        };

        const defaults = DESIGNER_DEFAULTS[resolvedDbType] ?? { pkType: "SERIAL", pkName: "id" };
        const defaultColumns = [
          {
            name: defaults.pkName,
            dataType: defaults.pkType,
            nullable: false,
            defaultValue: undefined,
            isPrimaryKey: true,
          },
        ] satisfies ColumnDefinitionInput[];

        const createCommand = buildDesignerCreateCommand(target, {
          tableName: nextName.trim(),
          columns: defaultColumns,
          primaryKey: [defaults.pkName],
        });

        stageBatchWithSingleHistoryEntry([createCommand]);
        return;
      }
      if (nextName === tableName) return;

      const updatedCreate = buildTableCreateCommand(columns, nextName);
      if (!updatedCreate) return;

      const updatedCommands: CrudCommand[] = [updatedCreate];
      fkCommands.forEach((cmd) => {
        const payload = cmd.payload as ForeignKeyAddPayload;
        const fkValue = buildForeignKeyValue(payload);
        if (!fkValue) return;

        const indexFromTag = getFkIndexFromTags(cmd.metadata.tags, fkTagPrefix);
        const columnName =
          (indexFromTag !== null ? columns[indexFromTag]?.name : undefined) ??
          payload.definition?.columns?.[0];
        if (!columnName) return;

        const resolvedIndex =
          indexFromTag !== null
            ? indexFromTag
            : columns.findIndex((col) => col.name === columnName);
        if (resolvedIndex < 0) return;

        const updatedFk = buildForeignKeyCommand(
          resolvedIndex,
          fkValue,
          columnName,
          cmd,
          nextName,
        );
        if (updatedFk && !("error" in updatedFk)) {
          updatedCommands.push(updatedFk as CrudCommand);
        }
      });

      stageBatchWithSingleHistoryEntry(updatedCommands);
    },
    [
      buildDesignerCreateCommand,
      buildForeignKeyCommand,
      buildTableCreateCommand,
      columns,
      connectionId,
      database,
      fkCommands,
      fkTagPrefix,
      resolvedDbType,
      resolvedSchema,
      resolveTargetTableName,
      stageBatchWithSingleHistoryEntry,
      tableCreateCommand,
      tableName,
    ],
  );

  const commitTableNameDraft = useCallback(
    (nextName: string) => {
      const trimmedName = nextName.trim();
      if (nextName !== tableName) {
        handleTableNameChange(nextName);
      }
      updateTabMetadata(panelId, tabId, {
        title: trimmedName || "New Table",
        table: trimmedName || undefined,
      });
    },
    [handleTableNameChange, panelId, tabId, tableName, updateTabMetadata],
  );

  // Handle blur - update crud store and tab title
  const handleTableNameBlur = useCallback(() => {
    commitTableNameDraft(tableNameDraft);
  }, [commitTableNameDraft, tableNameDraft]);

  // Generate SQL
  const generateSQL = useCallback(
    (tableNameOverride?: string) => {
      const resolvedTableName = (tableNameOverride ?? tableName).trim();
      if (!resolvedTableName || gridRows.length === 0) return "";

      const qi = (name: string) => quoteId(name, resolvedDbType);
      const fullTableName = formatTableName(resolvedSchema, resolvedTableName, resolvedDbType);

      const pkColumns = gridRows
        .filter((r) => r.column_meta.is_pk)
        .map((r) => r.column_name);

      const columnDefs = gridRows
        .map((col) => {
          let def = `  ${qi(col.column_name)} ${col.db_type}`;
          if (col.nullable === "NO") def += " NOT NULL";
          if (col.default?.trim()) def += ` DEFAULT ${col.default.trim()}`;
          if (col.check_constraint?.trim()) {
            def += ` CHECK (${normalizeCheckConstraint(col.check_constraint)})`;
          }
          // MySQL inline comment
          if (isMySQLCompatible(resolvedDbType) && col.comment?.trim()) {
            const escaped = col.comment.replace(/'/g, "''");
            def += ` COMMENT '${escaped}'`;
          }
          return def;
        })
        .join(",\n");

      const pkConstraint =
        pkColumns.length > 0
          ? `,\n  PRIMARY KEY (${pkColumns.map((c) => qi(c)).join(", ")})`
          : "";

      const foreignKeyConstraints = gridRows
        .map((col) => {
          if (!col.foreign_key) return null;
          const parsed = parseForeignKeyValue(col.foreign_key);
          if (!parsed) return null;
          const tableRef = parsed.schema
            ? `${qi(parsed.schema)}.${qi(parsed.table)}`
            : qi(parsed.table);
          return `  FOREIGN KEY (${qi(col.column_name)}) REFERENCES ${tableRef} (${qi(parsed.column)})`;
        })
        .filter((constraint): constraint is string => Boolean(constraint))
        .join(",\n");

      const allConstraints = [pkConstraint.trim(), foreignKeyConstraints]
        .filter(Boolean)
        .map((constraint) =>
          constraint.startsWith(",") ? constraint : `,\n${constraint}`,
        )
        .join("");

      const createTable = `CREATE TABLE ${fullTableName} (\n${columnDefs}${allConstraints}\n);`;

      // Only PostgreSQL supports COMMENT ON COLUMN
      const commentStatements: string[] = [];
      if (resolvedDbType === DbType.PostgreSQL) {
        gridRows.forEach((col) => {
          if (!col.comment || !col.comment.trim()) return;
          const columnRef = `${formatTableName(resolvedSchema, resolvedTableName, resolvedDbType)}.${qi(col.column_name)}`;
          const escaped = col.comment.replace(/'/g, "''");
          commentStatements.push(`COMMENT ON COLUMN ${columnRef} IS '${escaped}';`);
        });
      }

      const supportsPartialIndex = !isMySQLCompatible(resolvedDbType);

      // Generate CREATE INDEX statements from staged index commands
      const indexStatements = designerCommands
        .filter((cmd) => cmd.type === "index.create")
        .map((cmd) => {
          const payload = cmd.payload as IndexCreatePayload;
          const def = payload.definition;
          if (!def.name || def.columns.length === 0) return null;

          const cols = def.columns.map((c) => qi(c)).join(", ");
          const whereClause = supportsPartialIndex && def.where ? ` WHERE ${def.where}` : "";

          // MSSQL: index type is a keyword prefix (CLUSTERED/NONCLUSTERED/COLUMNSTORE), not USING
          // SQLite: no USING clause, only btree
          // PostgreSQL/MySQL: standard USING clause
          if (resolvedDbType === DbType.SQLServer) {
            const typePrefix = def.using && def.using !== "nonclustered"
              ? `${def.using.toUpperCase()} ` : "";
            const uniqueKeyword = def.unique ? "UNIQUE " : "";
            return `CREATE ${uniqueKeyword}${typePrefix}INDEX ${qi(def.name)} ON ${fullTableName} (${cols})${whereClause};`;
          }

          const uniqueKeyword = def.unique ? "UNIQUE " : "";
          const usingClause =
            def.using && def.using !== "btree" ? ` USING ${def.using}` : "";

          return `CREATE ${uniqueKeyword}INDEX ${qi(def.name)} ON ${fullTableName}${usingClause} (${cols})${whereClause};`;
        })
        .filter((s): s is string => Boolean(s));

      return [createTable, ...commentStatements, ...indexStatements].join("\n");
    },
    [tableName, gridRows, resolvedSchema, resolvedDbType, designerCommands],
  );

  const handleSave = useCallback(() => {
    if (!effectiveTableName) {
      toast.error("Please enter a table name");
      tableNameInputRef.current?.focus();
      return;
    }
    if (columns.length === 0) {
      toast.error("Please add at least one column");
      return;
    }

    // Validate all columns have names
    const invalidColumns = columns.filter((col) => !col.name.trim());
    if (invalidColumns.length > 0) {
      toast.error("All columns must have names");
      return;
    }

    // Validate no duplicate column names
    const columnNames = columns.map((col) => col.name.trim().toLowerCase());
    const duplicates = columnNames.filter((name, i) => name && columnNames.indexOf(name) !== i);
    if (duplicates.length > 0) {
      toast.error(`Duplicate column name: "${duplicates[0]}"`);
      return;
    }

    const invalidForeignKeys = new Set<string>();

    gridRows.forEach((col) => {
      const rawValue = col.foreign_key?.trim();
      if (!rawValue) return;
      const parsed = parseForeignKeyValue(rawValue);
      if (!parsed) {
        invalidForeignKeys.add(rawValue);
        return;
      }
    });

    if (invalidForeignKeys.size > 0) {
      toast.error("Invalid foreign key format", {
        description: "Use table.column or schema.table.column",
      });
      return;
    }

    // Validate indexes
    const invalidIndexes: string[] = [];
    const indexNames = new Set<string>();

    const currentIndexCommands = designerCommands.filter(
      (cmd) => cmd.type === "index.create",
    );

    currentIndexCommands.forEach((cmd) => {
      const payload = cmd.payload as IndexCreatePayload;
      const def = payload.definition;
      if (!def.name.trim()) {
        invalidIndexes.push("An index is missing a name");
      }
      if (def.columns.length === 0) {
        invalidIndexes.push(
          `Index "${def.name || "(unnamed)"}" has no columns`,
        );
      }
      const missingCols = def.columns.filter(
        (c) => !availableColumnNames.includes(c),
      );
      if (missingCols.length > 0) {
        invalidIndexes.push(
          `Index "${def.name}" references non-existent column(s): ${missingCols.join(", ")}`,
        );
      }
      if (def.name && indexNames.has(def.name)) {
        invalidIndexes.push(`Duplicate index name: "${def.name}"`);
      }
      if (def.name) indexNames.add(def.name);
    });

    if (invalidIndexes.length > 0) {
      toast.error("Invalid index definitions", {
        description: invalidIndexes[0],
      });
      return;
    }

    if (tableNameDraft !== tableName) {
      commitTableNameDraft(tableNameDraft);
    }

    setGlobalChangesDialogOpen(true);
  }, [
    availableColumnNames,
    columns,
    commitTableNameDraft,
    designerCommands,
    effectiveTableName,
    gridRows,
    tableName,
    tableNameDraft,
  ]);

  const handleCancel = useCallback(() => {
    if (designerCommands.length > 0) {
      unstageCommands(designerCommands.map((cmd) => cmd.id));
    }
    onCancel?.();
  }, [designerCommands, onCancel, unstageCommands]);

  return (
    <Tabs defaultValue="columns" className={cn("h-full gap-0", className)}>
      {/* Header */}

      <div className="flex items-center gap-2 py-1 px-0.5">
        <Input
          ref={tableNameInputRef}
          id="tableName"
          size="sm"
          className="w-56"
          value={tableNameDraft}
          onChange={(e) => {
            setTableNameDraft(e.target.value);
          }}
          onBlur={handleTableNameBlur}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              e.preventDefault();
              commitTableNameDraft(e.currentTarget.value);
              e.currentTarget.blur();
              return;
            }

            if (e.key === "Tab") {
              commitTableNameDraft(e.currentTarget.value);
              return;
            }

            if (e.key === "Escape") {
              e.preventDefault();
              setTableNameDraft(tableName);
              e.currentTarget.blur();
              return;
            }

            if (e.key === " ") {
              e.preventDefault();
              const input = e.currentTarget;
              const start = input.selectionStart ?? input.value.length;
              const end = input.selectionEnd ?? start;
              input.value =
                input.value.slice(0, start) + "_" + input.value.slice(end);
              input.setSelectionRange(start + 1, start + 1);
              setTableNameDraft(input.value);
            }
          }}
          placeholder="Enter table name"
        />
        <TabsList size="sm" className="w-fit">
          <TabsTrigger value="columns">Columns</TabsTrigger>
          <TabsTrigger value="indexes">
            Indexes{indexCommandCount > 0 ? ` (${indexCommandCount})` : ""}
          </TabsTrigger>
        </TabsList>
        <div className="ml-auto flex items-center gap-2">
          {onCancel && (
            <Button variant="outline" size="sm" onClick={handleCancel}>
              Cancel
            </Button>
          )}
          <Button
            size="sm"
            onClick={handleSave}
            disabled={!effectiveTableName || columns.length === 0}
          >
            Create Table
          </Button>
        </div>
      </div>

      <TabsContent
        value="columns"
        className="flex-1 min-h-0 mt-0"
        keepMounted
      >
        <DesignerColumnContextMenu
          hoveredRowRef={contextMenuRowRef}
          dbType={resolvedDbType}
          onAddColumn={handleRowAppended}
          onDuplicate={handleContextDuplicate}
          onTogglePrimaryKey={handleContextTogglePK}
          onSetNullable={handleContextSetNullable}
          onDeleteColumn={handleContextDeleteColumn}
        >
          <DataGridBase
            columns={sizedColumns}
            rowCount={gridRows.length}
            getCellContent={getCellContent}
            onCellEdited={handleCellEdited}
            customRenderers={customRenderers}
            onColumnResize={handleColumnResize}
            onColumnResizeEnd={handleColumnResizeEnd}
            onItemHovered={handleItemHovered}
            trailingRowOptions={{
              sticky: false,
              tint: false,
            }}
            onRowAppended={handleRowAppended}
            smoothScrollX
            smoothScrollY
            rowSelect="none"
            columnSelect="none"
          />
        </DesignerColumnContextMenu>
      </TabsContent>

      <TabsContent value="indexes" className="flex-1 min-h-0 mt-0">
        <IndexDesigner
          panelId={panelId}
          tabId={tabId}
          connectionId={connectionId}
          database={database}
          schema={resolvedSchema}
          availableColumns={availableColumnNames}
          tableName={effectiveTableName}
          foreignKeyColumns={foreignKeyColumnNames}
          designerTag={designerTag}
        />
      </TabsContent>

      <GlobalChangesDialog
        open={globalChangesDialogOpen}
        onOpenChange={setGlobalChangesDialogOpen}
        connectionId={connectionId}
        database={database}
        schema={resolvedSchema}
        table={tableTargetName}
        onCommitSuccess={() => {
          const finalTableName = effectiveTableName;
          const sql = generateSQL(finalTableName);
          onSave?.(finalTableName, sql);
          const committedTableKey = buildCrudTableKey({
            connectionId,
            database,
            schema: resolvedSchema,
            table: resolveTargetTableName(finalTableName),
          });
          discardChanges(committedTableKey);
          setGlobalChangesDialogOpen(false);
        }}
      />
    </Tabs>
  );
};

export default TableDesigner;
