import type { GridColumnV2 } from "@/components/DataGrid/types";

export const triggerColumns: GridColumnV2[] = [
  {
    id: "row_number",
    field: "row_number",
    title: "#",
    name: "#",
    width: 48,
    minWidth: 48,
    maxWidth: 80,
  } as GridColumnV2,
  {
    id: "name",
    field: "name",
    title: "Name",
    name: "Name",
    width: 200,
    minWidth: 120,
    maxWidth: 400,
  } as GridColumnV2,
  {
    id: "event",
    field: "event",
    title: "Event",
    name: "Event",
    width: 160,
    minWidth: 100,
    maxWidth: 240,
  } as GridColumnV2,
  {
    id: "timing",
    field: "timing",
    title: "Timing",
    name: "Timing",
    width: 120,
    minWidth: 80,
    maxWidth: 160,
  } as GridColumnV2,
  {
    id: "level",
    field: "level",
    title: "Level",
    name: "Level",
    width: 100,
    minWidth: 80,
    maxWidth: 140,
  } as GridColumnV2,
  {
    id: "enabled",
    field: "enabled",
    title: "Enabled",
    name: "Enabled",
    width: 96,
    minWidth: 72,
    maxWidth: 120,
  } as GridColumnV2,
  {
    id: "function",
    field: "function",
    title: "Function",
    name: "Function",
    width: 240,
    minWidth: 160,
  } as GridColumnV2,
  {
    id: "definition",
    field: "definition",
    title: "Definition",
    name: "Definition",
    width: 280,
    minWidth: 160,
  } as GridColumnV2,
  {
    id: "actions",
    field: "actions",
    title: "",
    name: "",
    width: 48,
    minWidth: 48,
    maxWidth: 48,
  } as GridColumnV2,
];
